version: "v.20250124.0"
services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:~/jenkins_home
    restart: always
volumes:
  jenkins_home:
